//**************************************************************************************************
//! @crc        761852129
//! @file       App_LibTab.h
//! @brief      Generate by: HYDAC Controller Project - Code Builder Tool Chain
//! @ecu        TTC580
//! @dll        1.2.7 (Build: 080)
//! @dll itf    1.7.0
//! @build      2023-04-03 16:35:10
//! @Match      07-04-01-04
//! @PDT        2.11.72.172
//! @PdtProjVer 0.0.0
//! @created    2025-04-18 16:40:50   HYDAC/HCP-CC
//**************************************************************************************************

#ifndef __APP_LIBTAB_H__
#define __APP_LIBTAB_H__

// INCLUDES ========================================================================================
#include <ItfCoreAllObj.h>

// GLOBAL VARIABLES ================================================================================

TVoid vAppAutoLibTable( TVoid );


// BLOCKs
extern        TBloCBus gCBus_tCAN_BUS0;
extern const TCBusCfg gCBus_ctCfg_CAN_BUS0;
extern        TBloCBus gCBus_tCAN_BUS1;
extern const TCBusCfg gCBus_ctCfg_CAN_BUS1;
extern        TBloCBus gCBus_tCAN_BUS2;
extern const TCBusCfg gCBus_ctCfg_CAN_BUS2;
extern        TBloCBus gCBus_tCAN_BUS3;
extern const TCBusCfg gCBus_ctCfg_CAN_BUS3;
extern        TBloCBus gCBus_tCAN_BUS4;
extern const TCBusCfg gCBus_ctCfg_CAN_BUS4;
extern        TBloInCur gInCur_tPressureBlockOscillationSensor;
extern const TInCurCfg gInCur_ctCfg_PressureBlockOscillationSensor;
extern        TBloInCur gInCur_tPressureBrakeSensor;
extern const TInCurCfg gInCur_ctCfg_PressureBrakeSensor;
extern        TBloInCur gInCur_tTemperatureTransmissionSensor;
extern const TInCurCfg gInCur_ctCfg_TemperatureTransmissionSensor;
extern        TBloInCur gInCur_tElectricPumpPressure;
extern const TInCurCfg gInCur_ctCfg_ElectricPumpPressure;
extern        TBloInFreq gInFreq_tOscillantAxleSpeedSensor;
extern const TInFreqCfg gInFreq_ctCfg_OscillantAxleSpeedSensor;
extern        TBloInFreq gInFreq_tFixeAxleSpeedSensor;
extern const TInFreqCfg gInFreq_ctCfg_FixeAxleSpeedSensor;
extern        TBloDig gDig_tEvDeflectorTransmission;
extern const TDigCfg gDig_ctCfg_EvDeflectorTransmission;
extern        TBloDig gDig_tEvUpMeasuringMast;
extern const TDigCfg gDig_ctCfg_EvUpMeasuringMast;
extern        TBloDig gDig_tEvDownMeasuringMast;
extern const TDigCfg gDig_ctCfg_EvDownMeasuringMast;
extern        TBloDig gDig_tEvServiceBrakeTrack;
extern const TDigCfg gDig_ctCfg_EvServiceBrakeTrack;
extern        TBloDig gDig_tEvPowerReduction;
extern const TDigCfg gDig_ctCfg_EvPowerReduction;
extern        TBloDig gDig_tSupplyRadioReceiver;
extern const TDigCfg gDig_ctCfg_SupplyRadioReceiver;
extern        TBloDig gDig_tBuzzerLynxMovingMachine;
extern const TDigCfg gDig_ctCfg_BuzzerLynxMovingMachine;
extern        TBloDig gDig_tWhiteLightAVG;
extern const TDigCfg gDig_ctCfg_WhiteLightAVG;
extern        TBloDig gDig_tWhiteLightAVD;
extern const TDigCfg gDig_ctCfg_WhiteLightAVD;
extern        TBloDig gDig_tRedLightAVG;
extern const TDigCfg gDig_ctCfg_RedLightAVG;
extern        TBloDig gDig_tRedLightAVD;
extern const TDigCfg gDig_ctCfg_RedLightAVD;
extern        TBloDig gDig_tWhiteLightARG;
extern const TDigCfg gDig_ctCfg_WhiteLightARG;
extern        TBloDig gDig_tWhiteLightARD;
extern const TDigCfg gDig_ctCfg_WhiteLightARD;
extern        TBloDig gDig_tRedLightARG;
extern const TDigCfg gDig_ctCfg_RedLightARG;
extern        TBloDig gDig_tRedLightARD;
extern const TDigCfg gDig_ctCfg_RedLightARD;
extern        TBloDig gDig_tSupplyPvgLeftTrack;
extern const TDigCfg gDig_ctCfg_SupplyPvgLeftTrack;
extern        TBloDig gDig_tSupplyPvgRightTrack;
extern const TDigCfg gDig_ctCfg_SupplyPvgRightTrack;
extern        TBloDig gDig_tWhiteTrailerLights;
extern const TDigCfg gDig_ctCfg_WhiteTrailerLights;
extern        TBloDig gDig_tRedTrailerLights;
extern const TDigCfg gDig_ctCfg_RedTrailerLights;
extern        TBloDig gDig_tSupplyAnaSensors;
extern const TDigCfg gDig_ctCfg_SupplyAnaSensors;
extern        TBloDig gDig_tPvgLeftTrackLowside;
extern const TDigCfg gDig_ctCfg_PvgLeftTrackLowside;
extern        TBloDig gDig_tPvgRightTrackLowside;
extern const TDigCfg gDig_ctCfg_PvgRightTrackLowside;
extern        TBloDig gDig_tReturnLowSideEvForwardPump;
extern const TDigCfg gDig_ctCfg_ReturnLowSideEvForwardPump;
extern        TBloDig gDig_tReturnLowSideEvBackwardPump;
extern const TDigCfg gDig_ctCfg_ReturnLowSideEvBackwardPump;
extern        TBloDig gDig_tKlaxonNeotec;
extern const TDigCfg gDig_ctCfg_KlaxonNeotec;
extern        TBloDig gDig_tEvUnBlockOscillationAxle;
extern const TDigCfg gDig_ctCfg_EvUnBlockOscillationAxle;
extern        TBloDig gDig_tEvParkBrakeAxleOscillant;
extern const TDigCfg gDig_ctCfg_EvParkBrakeAxleOscillant;
extern        TBloDig gDig_tEvParkBrakeAxleFixe;
extern const TDigCfg gDig_ctCfg_EvParkBrakeAxleFixe;
extern        TBloDig gDig_tEvServiceBrakeAxleOscillant;
extern const TDigCfg gDig_ctCfg_EvServiceBrakeAxleOscillant;
extern        TBloDig gDig_tEvUpAxleOscillant;
extern const TDigCfg gDig_ctCfg_EvUpAxleOscillant;
extern        TBloDig gDig_tEvUpAxleFixe;
extern const TDigCfg gDig_ctCfg_EvUpAxleFixe;
extern        TBloDig gDig_tEvDownAxleOscillant;
extern const TDigCfg gDig_ctCfg_EvDownAxleOscillant;
extern        TBloDig gDig_tEvDownAxleFixe;
extern const TDigCfg gDig_ctCfg_EvDownAxleFixe;
extern        TBloDig gDig_tEvServiceBrakeAxleFixe;
extern const TDigCfg gDig_ctCfg_EvServiceBrakeAxleFixe;
extern        TBloDig gDig_tNeonLights;
extern const TDigCfg gDig_ctCfg_NeonLights;
extern        TBloDig gDig_tEv2DeflectorTransmission;
extern const TDigCfg gDig_ctCfg_Ev2DeflectorTransmission;
extern        TBloDig gDig_tCoolingRelay;
extern const TDigCfg gDig_ctCfg_CoolingRelay;
extern        TBloDig gDig_tEv2ndParkBrakeAxleFixe;
extern const TDigCfg gDig_ctCfg_Ev2ndParkBrakeAxleFixe;
extern        TBloDig gDig_tEv2ndParkBrakeAxleOsci;
extern const TDigCfg gDig_ctCfg_Ev2ndParkBrakeAxleOsci;
extern        TBloDig gDig_tSupplyPvgTransRailElectric;
extern const TDigCfg gDig_ctCfg_SupplyPvgTransRailElectric;
extern        TBloDig gDig_tEvDevRailElectricMode;
extern const TDigCfg gDig_ctCfg_EvDevRailElectricMode;
extern        TBloDig gDig_tRelayCutOffVariatorElectric;
extern const TDigCfg gDig_ctCfg_RelayCutOffVariatorElectric;
extern        TBloDig gDig_tRelayEnableBattery;
extern const TDigCfg gDig_ctCfg_RelayEnableBattery;
extern        TBloOutVoltPro gOutVoltPro_tPvgLeftTrack;
extern const TOutVoltProCfg gOutVoltPro_ctCfg_PvgLeftTrack;
extern        TBloOutVoltPro gOutVoltPro_tPvgRightTrack;
extern const TOutVoltProCfg gOutVoltPro_ctCfg_PvgRightTrack;
extern        TBloOutVoltPro gOutVoltPro_tPvgTransRailElectric;
extern const TOutVoltProCfg gOutVoltPro_ctCfg_PvgTransRailElectric;
extern        TBloSwiNo gSwiNo_tRailHookSensor;
extern const TSwiNoCfg gSwiNo_ctCfg_RailHookSensor;
extern        TBloSwiNo gSwiNo_tInductiveRailSensor;
extern const TSwiNoCfg gSwiNo_ctCfg_InductiveRailSensor;
extern        TBloSwiNo gSwiNo_tCenteredTurret;
extern const TSwiNoCfg gSwiNo_ctCfg_CenteredTurret;
extern        TBloSwiNo gSwiNo_tWorkKeyTrackSide;
extern const TSwiNoCfg gSwiNo_ctCfg_WorkKeyTrackSide;
extern        TBloSwiNo gSwiNo_tWorkKeyBilateral;
extern const TSwiNoCfg gSwiNo_ctCfg_WorkKeyBilateral;
extern        TBloSwiNo gSwiNo_tWorkKeyCentred;
extern const TSwiNoCfg gSwiNo_ctCfg_WorkKeyCentred;
extern        TBloSwiNo gSwiNo_tAbutmentTurretTrackSide;
extern const TSwiNoCfg gSwiNo_ctCfg_AbutmentTurretTrackSide;
extern        TBloSwiNo gSwiNo_tAbutmentTurretCentredSide;
extern const TSwiNoCfg gSwiNo_ctCfg_AbutmentTurretCentredSide;
extern        TBloSwiNo gSwiNo_tOscillantAxleSpeedSensorDir;
extern const TSwiNoCfg gSwiNo_ctCfg_OscillantAxleSpeedSensorDir;
extern        TBloSwiNo gSwiNo_tFixeAxleSpeedSensorDir;
extern const TSwiNoCfg gSwiNo_ctCfg_FixeAxleSpeedSensorDir;
extern        TBloSwiNo gSwiNo_tTrailerGache;
extern const TSwiNoCfg gSwiNo_ctCfg_TrailerGache;
extern        TBloSwiNo gSwiNo_tMeasuringMastSensorFolded;
extern const TSwiNoCfg gSwiNo_ctCfg_MeasuringMastSensorFolded;
extern        TBloSwiNo gSwiNo_tAru1Contact;
extern const TSwiNoCfg gSwiNo_ctCfg_Aru1Contact;
extern        TBloSwiNo gSwiNo_tAru2Contact;
extern const TSwiNoCfg gSwiNo_ctCfg_Aru2Contact;
extern        TBloSwiNo gSwiNo_tAruRadio1Contact;
extern const TSwiNoCfg gSwiNo_ctCfg_AruRadio1Contact;
extern        TBloSwiNo gSwiNo_tAruRadio2Contact;
extern const TSwiNoCfg gSwiNo_ctCfg_AruRadio2Contact;
extern        TBloSwiNo gSwiNo_tStarterMotorState;
extern const TSwiNoCfg gSwiNo_ctCfg_StarterMotorState;
extern        TBloSwiNo gSwiNo_tAutorisationHighSpeedKey;
extern const TSwiNoCfg gSwiNo_ctCfg_AutorisationHighSpeedKey;
extern        TBloSwiNo gSwiNo_tValveInDownPositionSensor;
extern const TSwiNoCfg gSwiNo_ctCfg_ValveInDownPositionSensor;
extern        TBloCBuf gCBuf_tCBUS2_CBUF_SND_1;
extern const TCBufCfg gCBuf_ctCfg_CBUS2_CBUF_SND_1;
extern        TBloCBuf gCBuf_tCBUS2_CBUF_RCV_1;
extern const TCBufCfg gCBuf_ctCfg_CBUS2_CBUF_RCV_1;
extern        TBloCBuf gCBuf_tCBUS3_CBUF_SND_1;
extern const TCBufCfg gCBuf_ctCfg_CBUS3_CBUF_SND_1;
extern        TBloCBuf gCBuf_tCBUS3_CBUF_RCV_1;
extern const TCBufCfg gCBuf_ctCfg_CBUS3_CBUF_RCV_1;
extern        TBloCSnd gCSnd_tStart;
extern const TCSndCfg gCSnd_ctCfg_Start;
extern        TBloCSnd gCSnd_tWriteLed;
extern const TCSndCfg gCSnd_ctCfg_WriteLed;
extern        TBloCSnd gCSnd_tRadioCmd;
extern const TCSndCfg gCSnd_ctCfg_RadioCmd;
extern        TBloCSnd gCSnd_tStartSensor;
extern const TCSndCfg gCSnd_ctCfg_StartSensor;
extern        TBloCSnd gCSnd_tSendToEvision7;
extern const TCSndCfg gCSnd_ctCfg_SendToEvision7;
extern        TBloCSnd gCSnd_tDataSendToC1;
extern const TCSndCfg gCSnd_ctCfg_DataSendToC1;
extern        TBloCSnd gCSnd_tMsg2SendToEvision7;
extern const TCSndCfg gCSnd_ctCfg_Msg2SendToEvision7;
extern        TBloCSnd gCSnd_tMsg3SendToEvision7;
extern const TCSndCfg gCSnd_ctCfg_Msg3SendToEvision7;
extern        TBloCSnd gCSnd_tMessage_02;
extern const TCSndCfg gCSnd_ctCfg_Message_02;
extern        TBloCSnd gCSnd_tData2SendToC1;
extern const TCSndCfg gCSnd_ctCfg_Data2SendToC1;
extern        TBloCSnd gCSnd_tData3SendToC1;
extern const TCSndCfg gCSnd_ctCfg_Data3SendToC1;
extern        TBloCSnd gCSnd_tMsg4C0SendToEvision7;
extern const TCSndCfg gCSnd_ctCfg_Msg4C0SendToEvision7;
extern        TBloCSnd gCSnd_tFailuresC0SendToC1;
extern const TCSndCfg gCSnd_ctCfg_FailuresC0SendToC1;
extern        TBloCSnd gCSnd_tMsg5C0SendToEvision7;
extern const TCSndCfg gCSnd_ctCfg_Msg5C0SendToEvision7;
extern        TBloCSnd gCSnd_tMsg6C0SendToEvision7;
extern const TCSndCfg gCSnd_ctCfg_Msg6C0SendToEvision7;
extern        TBloCSnd gCSnd_tMsg7C0SendToEvision7;
extern const TCSndCfg gCSnd_ctCfg_Msg7C0SendToEvision7;
extern        TBloCSnd gCSnd_tMsg8C0SendToEvision7;
extern const TCSndCfg gCSnd_ctCfg_Msg8C0SendToEvision7;
extern        TBloCSnd gCSnd_tMsg9C0SendToEvision7;
extern const TCSndCfg gCSnd_ctCfg_Msg9C0SendToEvision7;
extern        TBloCSnd gCSnd_tMsg9C0SendToEvision7_1;
extern const TCSndCfg gCSnd_ctCfg_Msg9C0SendToEvision7_1;
extern        TBloCSnd gCSnd_tMsg2C0SendToOpus;
extern const TCSndCfg gCSnd_ctCfg_Msg2C0SendToOpus;
extern        TBloCSnd gCSnd_tMsg3C0SendToOpus;
extern const TCSndCfg gCSnd_ctCfg_Msg3C0SendToOpus;
extern        TBloCSnd gCSnd_tMsg4C0SendToOpus;
extern const TCSndCfg gCSnd_ctCfg_Msg4C0SendToOpus;
extern        TBloCSnd gCSnd_tMsg5C0SendToOpus;
extern const TCSndCfg gCSnd_ctCfg_Msg5C0SendToOpus;
extern        TBloCSnd gCSnd_tMsg6C0SendToOpus;
extern const TCSndCfg gCSnd_ctCfg_Msg6C0SendToOpus;
extern        TBloCSnd gCSnd_tMsg7C0SendToOpus;
extern const TCSndCfg gCSnd_ctCfg_Msg7C0SendToOpus;
extern        TBloCSnd gCSnd_tMsg8C0SendToOpus;
extern const TCSndCfg gCSnd_ctCfg_Msg8C0SendToOpus;
extern        TBloCSnd gCSnd_tMsg1C0SendToOpus;
extern const TCSndCfg gCSnd_ctCfg_Msg1C0SendToOpus;
extern        TBloCSnd gCSnd_tData4C0SendToC1;
extern const TCSndCfg gCSnd_ctCfg_Data4C0SendToC1;
extern        TBloCSnd gCSnd_tMsg11C0SendToEvision7;
extern const TCSndCfg gCSnd_ctCfg_Msg11C0SendToEvision7;
extern        TBloCSnd gCSnd_tMsg9C0SendToOpus;
extern const TCSndCfg gCSnd_ctCfg_Msg9C0SendToOpus;
extern        TBloCSnd gCSnd_tMsg10C0SendToOpus;
extern const TCSndCfg gCSnd_ctCfg_Msg10C0SendToOpus;
extern        TBloCSnd gCSnd_tSyncFrame;
extern const TCSndCfg gCSnd_ctCfg_SyncFrame;
extern        TBloCSnd gCSnd_tMsg12C0SendToEvision7;
extern const TCSndCfg gCSnd_ctCfg_Msg12C0SendToEvision7;
extern        TBloCSnd gCSnd_tMsg13C0SendToEvision7;
extern const TCSndCfg gCSnd_ctCfg_Msg13C0SendToEvision7;
extern        TBloCSnd gCSnd_tDatalogger;
extern const TCSndCfg gCSnd_ctCfg_Datalogger;
extern        TBloCSnd gCSnd_tSdo_Request_Encodeur_Turret;
extern const TCSndCfg gCSnd_ctCfg_Sdo_Request_Encodeur_Turret;
extern        TBloCSnd gCSnd_tSdo_Request_Encodeur_Turret2;
extern const TCSndCfg gCSnd_ctCfg_Sdo_Request_Encodeur_Turret2;
extern        TBloCSnd gCSnd_tData5C0SendToC1;
extern const TCSndCfg gCSnd_ctCfg_Data5C0SendToC1;
extern        TBloCSnd gCSnd_tMsg11C0SendToOpus;
extern const TCSndCfg gCSnd_ctCfg_Msg11C0SendToOpus;
extern        TBloCSnd gCSnd_tMsg14C0SendToEvision7;
extern const TCSndCfg gCSnd_ctCfg_Msg14C0SendToEvision7;
extern        TBloCSnd gCSnd_tMsg15C0SendToEvision7;
extern const TCSndCfg gCSnd_ctCfg_Msg15C0SendToEvision7;
extern        TBloCSnd gCSnd_tHMG_1;
extern const TCSndCfg gCSnd_ctCfg_HMG_1;
extern        TBloCSnd gCSnd_tHMG_2;
extern const TCSndCfg gCSnd_ctCfg_HMG_2;
extern        TBloCSnd gCSnd_tHMG_3;
extern const TCSndCfg gCSnd_ctCfg_HMG_3;
extern        TBloCSnd gCSnd_tDMC_TxSdo;
extern const TCSndCfg gCSnd_ctCfg_DMC_TxSdo;
extern        TBloCSnd gCSnd_tNMT;
extern const TCSndCfg gCSnd_ctCfg_NMT;
extern        TBloCSnd gCSnd_tDMC_TxPdo1_DC;
extern const TCSndCfg gCSnd_ctCfg_DMC_TxPdo1_DC;
extern        TBloCSnd gCSnd_tDMC_TxPdo2_BCL;
extern const TCSndCfg gCSnd_ctCfg_DMC_TxPdo2_BCL;
extern        TBloCRcv gCRcv_tHeartBeat;
extern const TCRcvCfg gCRcv_ctCfg_HeartBeat;
extern        TBloCRcv gCRcv_tReadAnalogInput;
extern const TCRcvCfg gCRcv_ctCfg_ReadAnalogInput;
extern        TBloCRcv gCRcv_tReadOnOfffInput;
extern const TCRcvCfg gCRcv_ctCfg_ReadOnOfffInput;
extern        TBloCRcv gCRcv_tHeartBeatDeversFrame;
extern const TCRcvCfg gCRcv_ctCfg_HeartBeatDeversFrame;
extern        TBloCRcv gCRcv_tDeversFrame1;
extern const TCRcvCfg gCRcv_ctCfg_DeversFrame1;
extern        TBloCRcv gCRcv_tEncodeurTurret1;
extern const TCRcvCfg gCRcv_ctCfg_EncodeurTurret1;
extern        TBloCRcv gCRcv_tEncodeurTurret2;
extern const TCRcvCfg gCRcv_ctCfg_EncodeurTurret2;
extern        TBloCRcv gCRcv_tMsg1C0RcvFromEvision7;
extern const TCRcvCfg gCRcv_ctCfg_Msg1C0RcvFromEvision7;
extern        TBloCRcv gCRcv_tDataRcvFromC1;
extern const TCRcvCfg gCRcv_ctCfg_DataRcvFromC1;
extern        TBloCRcv gCRcv_tHeartBeatEncodeurTurret1;
extern const TCRcvCfg gCRcv_ctCfg_HeartBeatEncodeurTurret1;
extern        TBloCRcv gCRcv_tPDO3_48XS;
extern const TCRcvCfg gCRcv_ctCfg_PDO3_48XS;
extern        TBloCRcv gCRcv_tPDO4_48XS;
extern const TCRcvCfg gCRcv_ctCfg_PDO4_48XS;
extern        TBloCRcv gCRcv_tSRDO2_48XS;
extern const TCRcvCfg gCRcv_ctCfg_SRDO2_48XS;
extern        TBloCRcv gCRcv_tSRDO3_48XS;
extern const TCRcvCfg gCRcv_ctCfg_SRDO3_48XS;
extern        TBloCRcv gCRcv_tMastMeasure;
extern const TCRcvCfg gCRcv_ctCfg_MastMeasure;
extern        TBloCRcv gCRcv_tData2RdvFromC1;
extern const TCRcvCfg gCRcv_ctCfg_Data2RdvFromC1;
extern        TBloCRcv gCRcv_tHearbeat_48XS;
extern const TCRcvCfg gCRcv_ctCfg_Hearbeat_48XS;
extern        TBloCRcv gCRcv_tPDO1_48XS;
extern const TCRcvCfg gCRcv_ctCfg_PDO1_48XS;
extern        TBloCRcv gCRcv_tPDO2_48XS;
extern const TCRcvCfg gCRcv_ctCfg_PDO2_48XS;
extern        TBloCRcv gCRcv_tSRDO1_48XS;
extern const TCRcvCfg gCRcv_ctCfg_SRDO1_48XS;
extern        TBloCRcv gCRcv_tData3RcvFromC1;
extern const TCRcvCfg gCRcv_ctCfg_Data3RcvFromC1;
extern        TBloCRcv gCRcv_tDeversFrame2;
extern const TCRcvCfg gCRcv_ctCfg_DeversFrame2;
extern        TBloCRcv gCRcv_tFAiluresC1SendToC0;
extern const TCRcvCfg gCRcv_ctCfg_FAiluresC1SendToC0;
extern        TBloCRcv gCRcv_tMsg1RcvFromOpus;
extern const TCRcvCfg gCRcv_ctCfg_Msg1RcvFromOpus;
extern        TBloCRcv gCRcv_tData4C1SendToC0;
extern const TCRcvCfg gCRcv_ctCfg_Data4C1SendToC0;
extern        TBloCRcv gCRcv_tEmergencyEncodeurTurret1;
extern const TCRcvCfg gCRcv_ctCfg_EmergencyEncodeurTurret1;
extern        TBloCRcv gCRcv_tEmergencyEncodeurTurret2;
extern const TCRcvCfg gCRcv_ctCfg_EmergencyEncodeurTurret2;
extern        TBloCRcv gCRcv_tEmergencyMastMeasure;
extern const TCRcvCfg gCRcv_ctCfg_EmergencyMastMeasure;
extern        TBloCRcv gCRcv_tPDO5_48XS;
extern const TCRcvCfg gCRcv_ctCfg_PDO5_48XS;
extern        TBloCRcv gCRcv_tHeartBeatEncodeurTurret2;
extern const TCRcvCfg gCRcv_ctCfg_HeartBeatEncodeurTurret2;
extern        TBloCRcv gCRcv_tPDO6_48XS;
extern const TCRcvCfg gCRcv_ctCfg_PDO6_48XS;
extern        TBloCRcv gCRcv_tSdo_Answer_Encodeur_Turret1;
extern const TCRcvCfg gCRcv_ctCfg_Sdo_Answer_Encodeur_Turret1;
extern        TBloCRcv gCRcv_tSdo_Answer_Encodeur_Turret2;
extern const TCRcvCfg gCRcv_ctCfg_Sdo_Answer_Encodeur_Turret2;
extern        TBloCRcv gCRcv_tData5C1SendToC0;
extern const TCRcvCfg gCRcv_ctCfg_Data5C1SendToC0;
extern        TBloCRcv gCRcv_tFlashBatteryRpdo1_0;
extern const TCRcvCfg gCRcv_ctCfg_FlashBatteryRpdo1_0;
extern        TBloCRcv gCRcv_tFlashBatteryRpdo1_2;
extern const TCRcvCfg gCRcv_ctCfg_FlashBatteryRpdo1_2;
extern        TBloCRcv gCRcv_tFlashBatteryRpdo2_0;
extern const TCRcvCfg gCRcv_ctCfg_FlashBatteryRpdo2_0;
extern        TBloCRcv gCRcv_tFlashBatteryRpdo3_0;
extern const TCRcvCfg gCRcv_ctCfg_FlashBatteryRpdo3_0;
extern        TBloCRcv gCRcv_tFlashBatteryRpdo3_3;
extern const TCRcvCfg gCRcv_ctCfg_FlashBatteryRpdo3_3;
extern        TBloCRcv gCRcv_tDMC_Heartbeat_HB;
extern const TCRcvCfg gCRcv_ctCfg_DMC_Heartbeat_HB;
extern        TBloCRcv gCRcv_tDMC_RxSdo;
extern const TCRcvCfg gCRcv_ctCfg_DMC_RxSdo;
extern        TBloCRcv gCRcv_tDMC_RxPdo1_MS;
extern const TCRcvCfg gCRcv_ctCfg_DMC_RxPdo1_MS;
extern        TBloCRcv gCRcv_tDMC_RxPdo2_DS;
extern const TCRcvCfg gCRcv_ctCfg_DMC_RxPdo2_DS;
extern        TBloCRcv gCRcv_tDMC_RxPdo3_CS;
extern const TCRcvCfg gCRcv_ctCfg_DMC_RxPdo3_CS;
extern        TBloPro gPro_tEvForwardPump;
extern const TProCfg gPro_ctCfg_EvForwardPump;
extern        TBloPro gPro_tEvBackwardPump;
extern const TProCfg gPro_ctCfg_EvBackwardPump;
extern        TBloSwiNc gSwiNc_tUpOscillantAxle;
extern const TSwiNcCfg gSwiNc_ctCfg_UpOscillantAxle;
extern        TBloSwiNc gSwiNc_tUpFixeAxle;
extern const TSwiNcCfg gSwiNc_ctCfg_UpFixeAxle;
extern        TBloSwiNc gSwiNc_tUpMastSensorNC;
extern const TSwiNcCfg gSwiNc_ctCfg_UpMastSensorNC;
extern        TBloSwiDblNoNc gSwiDblNoNc_tFrameRotationSensor1;
extern const TSwiDblNoNcCfg gSwiDblNoNc_ctCfg_FrameRotationSensor1;
extern        TBloSwiDblNoNc gSwiDblNoNc_tFrameRotationSensor2;
extern const TSwiDblNoNcCfg gSwiDblNoNc_ctCfg_FrameRotationSensor2;
extern        TBloErr gErr_tSpecificErrorC0;
extern const TErrCfg gErr_ctCfg_SpecificErrorC0;
extern        TBloErr gErr_tSpecificErrorC0_2;
extern const TErrCfg gErr_ctCfg_SpecificErrorC0_2;
extern        TBloErr gErr_tSpecificErrorC0_3;
extern const TErrCfg gErr_ctCfg_SpecificErrorC0_3;
extern        TBloErr gErr_tSpecificErrorC0_4;
extern const TErrCfg gErr_ctCfg_SpecificErrorC0_4;
extern        TBloErr gErr_tSpecificErrorC0_5;
extern const TErrCfg gErr_ctCfg_SpecificErrorC0_5;
extern        TBloErr gErr_tSpecificErrorC0_6;
extern const TErrCfg gErr_ctCfg_SpecificErrorC0_6;
extern        TBloErr gErr_tSpecificErrorC0_7;
extern const TErrCfg gErr_ctCfg_SpecificErrorC0_7;
extern        TBloErr gErr_tSpecificErrorC0_8;
extern const TErrCfg gErr_ctCfg_SpecificErrorC0_8;
extern        TBloErr gErr_tSpecificErrorC0_9;
extern const TErrCfg gErr_ctCfg_SpecificErrorC0_9;
extern        TBloSwiDblNcNo gSwiDblNcNo_tDownOscillantAxle;
extern const TSwiDblNcNoCfg gSwiDblNcNo_ctCfg_DownOscillantAxle;
extern        TBloSwiDblNcNo gSwiDblNcNo_tDownFixeAxle;
extern const TSwiDblNcNoCfg gSwiDblNcNo_ctCfg_DownFixeAxle;
extern        TBloSil gSil_tEcu0_Safety;
extern const TSilCfg gSil_ctCfg_Ecu0_Safety;
extern        TBloSil gSil_tEcu1_Safety;
extern const TSilCfg gSil_ctCfg_Ecu1_Safety;
extern        TBloSil gSil_tEcuSil;
extern const TSilCfg gSil_ctCfg_EcuSil;
extern        TBloSil gSil_tSensorSupply;
extern const TSilCfg gSil_ctCfg_SensorSupply;
extern        TBloSil gSil_tErrList;
extern const TSilCfg gSil_ctCfg_ErrList;

// STRUCTs


#endif // __APP_LIBTAB_H__

